# Generated by Django 4.2 on 2026-05-01 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_quantity_lot', message='La quantitat per lot ha de ser un número enter major a 0.', regex='^[1-9]+$')])),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lot',
            },
        ),
        migrations.CreateModel(
            name='Magatzem',
            fields=[
                ('codi_magatzem', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El codi ha de tenir exactament 8 caràcters.', regex='^[a-zA-Z0-9]{8}$')])),
            ],
            options={
                'verbose_name': 'Magatzem',
                'verbose_name_plural': 'Magatzems',
                'db_table': 'magatzem',
            },
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id_producte', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='id_producte_invalid_length', message='El ID del producte ha de tenir exactament 12 caràcters.', regex='^[a-zA-Z0-9]{12}$')])),
                ('codi_proveidor', models.CharField(max_length=50)),
                ('estoc_total', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(code='invalid_number_estoc_total', message='L’estoc total ha de ser un número entero no negativo.', regex='^[0-9]+$')])),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.RegexValidator(code='invalid_price_producte', message='El preu ha de ser un número decimal i fins a dos decimals.', regex='^\\d+(\\.\\d{1,2})?$')])),
                ('categoria', models.CharField(choices=[('petit', 'Petit'), ('mitja', 'Mitjà'), ('gran', 'Gran'), ('gegant', 'Gegant')], max_length=6)),
            ],
            options={
                'verbose_name': 'Producte',
                'verbose_name_plural': 'Productes',
                'db_table': 'producte',
            },
        ),
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('telefon', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('superior', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Treballador',
                'verbose_name_plural': 'Treballadors',
                'db_table': 'treballador',
            },
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id_ubicacio', models.AutoField(primary_key=True, serialize=False)),
                ('passadis', models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_length', message='El passadís ha de tenir exactament 3 caràcters.', regex='^[a-zA-Z0-9]{3}$')])),
                ('estant', models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_length', message='L’estant ha de tenir exactament 3 caràcters.', regex='^[a-zA-Z0-9]{3}$')])),
                ('alcada', models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_length', message='L’alcada ha de tenir exactament 3 caràcters.', regex='^[a-zA-Z0-9]{3}$')])),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacions', to='inventari.magatzem')),
            ],
            options={
                'verbose_name': 'Ubicació',
                'verbose_name_plural': 'Ubicacions',
                'db_table': 'ubicacio',
            },
        ),
        migrations.AddConstraint(
            model_name='producte',
            constraint=models.CheckConstraint(check=models.Q(('id_producte__regex', '^[a-zA-Z0-9]{12}$')), name='id_producte_longitud_exacta_12'),
        ),
        migrations.AddConstraint(
            model_name='producte',
            constraint=models.CheckConstraint(check=models.Q(('estoc_total__gte', 0)), name='estoc_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producte',
            constraint=models.CheckConstraint(check=models.Q(('preu__regex', '^\\d+(\\.\\d{1,2})?$')), name='formato_precio_invalido'),
        ),
        migrations.AddConstraint(
            model_name='magatzem',
            constraint=models.CheckConstraint(check=models.Q(('codi_magatzem__regex', '^[a-zA-Z0-9]{8}$')), name='longitud_exacta_8'),
        ),
        migrations.AddField(
            model_name='lot',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='inventari.producte'),
        ),
        migrations.AddField(
            model_name='lot',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='inventari.treballador'),
        ),
        migrations.AddField(
            model_name='lot',
            name='ubicacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots', to='inventari.ubicacio'),
        ),
        migrations.AddConstraint(
            model_name='ubicacio',
            constraint=models.UniqueConstraint(fields=('magatzem', 'passadis', 'estant', 'alcada'), name='unique_ubicacio_total'),
        ),
        migrations.AddConstraint(
            model_name='ubicacio',
            constraint=models.CheckConstraint(check=models.Q(('passadis__regex', '^[a-zA-Z0-9]{3}$')), name='passadis_longitud_exacta_3'),
        ),
        migrations.AddConstraint(
            model_name='ubicacio',
            constraint=models.CheckConstraint(check=models.Q(('estant__regex', '^[a-zA-Z0-9]{3}$')), name='estant_longitud_exacta_3'),
        ),
        migrations.AddConstraint(
            model_name='ubicacio',
            constraint=models.CheckConstraint(check=models.Q(('alcada__regex', '^[a-zA-Z0-9]{3}$')), name='alcada_longitud_exacta_3'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('ubicacio', 'producte')},
        ),
    ]
