# Generated by Django 4.2 on 2026-05-26 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventari', '0003_treballador_magatzem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='categoria',
            field=models.CharField(choices=[('petit', 'Petit'), ('mitja', 'Mitjà'), ('gran', 'Gran'), ('gegant', 'Gegant')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='producte',
            name='estoc_total',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.RegexValidator(code='invalid_number_estoc_total', message="L'estoc total ha de ser un número entero no negativo.", regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='ubicacio',
            name='alcada',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_length', message="L'alcada ha de tenir exactament 3 caràcters.", regex='^[a-zA-Z0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='ubicacio',
            name='estant',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_length', message="L'estant ha de tenir exactament 3 caràcters.", regex='^[a-zA-Z0-9]{3}$')]),
        ),
    ]
