# Generated by Django 4.2 on 2026-05-01 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('nif', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El NIF ha de tenir exactament 8 caràcters.', regex='^[a-zA-Z0-9]{8}$')])),
                ('nom', models.CharField(max_length=100)),
                ('correu_electronic', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empresa', serialize=False, to='clients.client')),
                ('adressa', models.CharField(max_length=200)),
                ('enviament', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empreses',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual', serialize=False, to='clients.client')),
                ('telefon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
                'db_table': 'individual',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('nif__regex', '^[a-zA-Z0-9]{8}$')), name='nif_longitud_exacta_8'),
        ),
    ]
