# Generated by Django 4.2 on 2026-05-12 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='nif_longitud_exacta_8',
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El NIF ha de tenir exactament 8 caràcters.', regex='^[a-zA-Z0-9]{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('nif__regex', '^[a-zA-Z0-9]{9}$')), name='nif_longitud_exacta_9'),
        ),
    ]
