# Generated by Django 4.2 on 2026-05-12 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_nif_longitud_exacta_8_alter_client_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El NIF ha de tenir exactament 9 caràcters.', regex='^[a-zA-Z0-9]{9}$')]),
        ),
    ]
