# Generated by Django 4.2 on 2026-05-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventari', '0003_treballador_magatzem'),
        ('clients', '0003_alter_client_nif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMagatzem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_magatzems', to='clients.client')),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_magatzems', to='inventari.magatzem')),
            ],
            options={
                'verbose_name': 'Client-Magatzem',
                'db_table': 'client_magatzem',
                'unique_together': {('client', 'magatzem')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='magatzems',
            field=models.ManyToManyField(blank=True, related_name='clients', through='clients.ClientMagatzem', to='inventari.magatzem'),
        ),
    ]
