# Generated by Django 4.2 on 2026-05-01 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventari', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El ID de la comanda ha de tenir exactament 5 caràcters.', regex='^[a-zA-Z0-9]{5}$')])),
                ('metode_pagament', models.IntegerField(choices=[(1, 'Targeta'), (2, 'Transferència'), (3, 'Efectiu')])),
                ('enviament', models.BooleanField(default=False)),
                ('import_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandes',
                'db_table': 'comanda',
            },
        ),
        migrations.CreateModel(
            name='Paquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField()),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquets', to='comandes.comanda')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquets', to='inventari.producte')),
            ],
            options={
                'verbose_name': 'Paquet',
                'verbose_name_plural': 'Paquets',
                'db_table': 'paquet',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_length', message='El ID de la factura ha de tenir exactament 5 caràcters.', regex='^[a-zA-Z0-9]{5}$')])),
                ('import_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Factures',
                'db_table': 'factura',
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandes', to='comandes.factura'),
        ),
        migrations.AddConstraint(
            model_name='paquet',
            constraint=models.UniqueConstraint(fields=('comanda', 'producte'), name='comanda_producte_unic'),
        ),
        migrations.AddConstraint(
            model_name='paquet',
            constraint=models.CheckConstraint(check=models.Q(('quantitat', 0), _negated=True), name='quantitat_no_es_zero'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(check=models.Q(('id_factura__regex', '^[a-zA-Z0-9]{5}$')), name='longitud_exacta_5'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.CheckConstraint(check=models.Q(('id_comanda__regex', '^[a-zA-Z0-9]{5}$')), name='id_comanda_longitud_exacta_5'),
        ),
    ]
