# Generated by Django 4.2 on 2026-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0002_comanda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='enviament',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='data',
            field=models.DateField(db_index=True),
        ),
    ]
