# Generated by Django 4.2 on 2026-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0003_indexes_data_enviament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='metode_pagament',
            field=models.IntegerField(blank=True, choices=[(1, 'Targeta'), (2, 'Transferència'), (3, 'Efectiu')], null=True),
        ),
    ]
