# Generated by Django 4.2 on 2026-05-27 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comandes', '0004_comanda_metode_pagament_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='preparat',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='comanda',
            name='preparat_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandes_preparades', to=settings.AUTH_USER_MODEL),
        ),
    ]
